project:
  type: website

website:
  title: "Top YouTube Channels"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



